--- 
- hosts: linuxservers
  remote_user: root
  gather_facts: true
  become: yes
  become_method: sudo

  vars:
    xi_ip: '<NagiosXi-server-IP>'
    api_key: 'Nagios-API'

  roles: 
        - {role: nrpe-role}
        - {role: register-host}
        - {role: unregister-host}
